language: java
install: true

jdk:
  - oraclejdk11

addons:
  sonarcloud:
    organization: "s-schizophrene-trio"
    token:
      secure: $SONAR_TOKEN

script:
  - ./gradlew build --scan -s
  - sonar-scanner

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
